In [1]:
import numpy as np 
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

yes, data type of list_ and array_list is different

In [2]:
type(list_)

list

In [3]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
for i in list_ :
    print(f"Data type of element '{i}' in list_: {type(i)}")

for i in array_list :
    print(f"Data type of element '{i}' in array_liat: {type(i)}")

Data type of element '1' in list_: <class 'str'>
Data type of element '2' in list_: <class 'str'>
Data type of element '3' in list_: <class 'str'>
Data type of element '4' in list_: <class 'str'>
Data type of element '5' in list_: <class 'str'>
Data type of element '1' in array_liat: <class 'numpy.str_'>
Data type of element '2' in array_liat: <class 'numpy.str_'>
Data type of element '3' in array_liat: <class 'numpy.str_'>
Data type of element '4' in array_liat: <class 'numpy.str_'>
Data type of element '5' in array_liat: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

yes, there is difference b/w the datatype of element of  list_ and array_list

In [8]:
array_list = np.array(object = list_, dtype = int)

In [10]:
array_list

array([1, 2, 3, 4, 5])

In [15]:
for i in list_ :
    print(f"Data type of element '{i}' in list_: {type(i)} ")

for i in array_list :
    print(f"Data type of element '{i}' in list_: {type(i)} ")


Data type of element '1' in list_: <class 'str'> 
Data type of element '2' in list_: <class 'str'> 
Data type of element '3' in list_: <class 'str'> 
Data type of element '4' in list_: <class 'str'> 
Data type of element '5' in list_: <class 'str'> 
Data type of element '1' in list_: <class 'numpy.int64'> 
Data type of element '2' in list_: <class 'numpy.int64'> 
Data type of element '3' in list_: <class 'numpy.int64'> 
Data type of element '4' in list_: <class 'numpy.int64'> 
Data type of element '5' in list_: <class 'numpy.int64'> 


In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [17]:
#1 shape 
np.shape(num_array)

(2, 3)

In [18]:
#2 size
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [22]:
zero_matrix = np.zeros((3,3))

In [24]:
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [26]:
identity_matrix = np.identity(5)

In [28]:
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
# 
data1=np.diag([1,1,1,1,1])

In [32]:
data1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])